- README.md
> set up the README.md file

- package-lock.json
- package.json
- src/app.js
- src/index.js
- src/routes/index.js
- src/views/layouts/main.hbs
- src/views/partials/header.hbs
> set up code 1

- package-lock.json
- package.json
- tests/test.js
Student will be added to the api.
> Student will be added to the api

- package-lock.json
- package.json
- src/routes/index.js
> route file

- public/index.html
- public/style.css
I changed the name for the input box
deleted the h2 (description) in the html and in the css
> change the input name

- package.json
> Fixed an error

- public/index.html
- src/views/home.hbs
- src/views/layouts/main.hbs
- src/views/register.hbs
> Changing the code

- database/db_connection.js
- package-lock.json
- package.json
- public/index.html
- src/app.js
- src/routes/index.js
changing the path of the register requrie
const  register = require('../views/register');
> changing the path

- src/views/eightGrade.hbs
- src/views/ninethGrade.hbs
- src/views/seventhGrade.hbs
> classes pages

- src/helpers/validation.js
> validation

- package-lock.json
- package.json
- src/helpers/index.js
- src/model/index.js
- src/routes/index.js
- src/views/home.hbs
Added the cookies in helpers index.js.
> Added the cookies

- src/helpers/hashing.js
- src/routes/index.js
I coded the hashing file in the helpers and connected it in the router index.js
> coding the hashing files

- package.json
- src/routes/index.js
> update the files

- package.json
- src/app.js
- src/helpers/cookies.js
- src/routes/index.js
- src/views/class.hbs
- src/views/home.hbs
Added the action method in html to open another page in pressing on the buttons.
> Added the action method

- package-lock.json
- package.json
- src/routes/index.js
Changing the code in index.js file (routes)
> Changing the code 

- src/helpers/validate.js
- src/model/index.js
- tests/db_test.js
- tests/server_test.js
change the error status to 404
> change the status code

- package.json
- public/register.css
- public/style.css
- src/database/db_build.js
- src/database/db_build.sql
- src/database/db_connection.js
- src/database/queries/getData.js
- src/database/queries/postData.js
- src/views/layouts/main.hbs
- tests/db_testsss.js
- tests/test.js
testing the database in file db_test
> testing the database

- src/helpers/validate.js
- src/helpers/validation.js
- src/routes/index.js
- src/views/eightGrade.hbs
- src/views/home.hbs
- src/views/ninethGrade.hbs
- src/views/register.hbs
- src/views/seventhGrade.hbs
Sign up validation is required, but the login button to require the validation still not working.
> Sign up validation is required

- src/views/register.hbs
> Fixing the file

- src/views/class.hbs
- src/views/register.hbs
Sign up button is working! :confetti_ball:
> Sign up button is working!

- public/index.js
Fixing issue#66 well done :+1:
> Fixing issue#66

- src/model/index.js
- src/routes/index.js
> fixing issue

- src/routes/index.js
deliting require
const dataBase = require("./../model")
> deliting require

- public/icon.css
- src/helpers/validation.js
- src/views/layouts/main.hbs
- src/views/partials/header.hbs
- src/views/partials/lotusIcon.hbs
> fixing and deliting

- src/helpers/validation.js
- src/routes/index.js
> Update the app

- src/helpers/validation.js
- src/routes/index.js
- src/views/home.hbs
>  Validation

- src/routes/index.js
- src/views/home.hbs
- src/views/register.hbs
Changed the sign up button, check it out.
> Changed the sign up button

- public/index.js
- src/database/db_build.js
- src/database/db_build.sql
- src/database/db_connection.js
- src/helpers/validation.js
- src/routes/index.js
- src/views/layouts/main.hbs
- src/views/register.hbs
I fixed the database and its working!! We are receiving the info of the user!!!!
> Fixing the db

- README.md
- public/index.js
- src/database/db_build.js
- src/database/db_build.sql
- src/database/db_connection.js
- src/helpers/validation.js
- src/routes/index.js
- src/views/layouts/main.hbs
- src/views/partials/header.hbs
- src/views/partials/logOut.hbs
- src/views/partials/logout.hbs
> Fixing bugs
